create TABLE IF NOT EXISTS genre (
  genre_id integer PRIMARY KEY,
  genre_name varchar(200) NOT NULL
);

create TABLE IF NOT EXISTS mpa_rating (
  mpa_rating_id integer PRIMARY KEY,
  mpa_name varchar(200) NOT NULL UNIQUE
);

create TABLE IF NOT EXISTS films (
  film_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  description text,
  release_Date date,
  duration integer CHECK (duration > 0),
  rating_id integer NOT NULL REFERENCES mpa_rating (mpa_rating_id)
);

create TABLE IF NOT EXISTS users (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(200) NOT NULL,
  login varchar(200) NOT NULL UNIQUE,
  name varchar(200),
  birthday date
);

create TABLE IF NOT EXISTS friends (
  user_id1 integer NOT NULL REFERENCES users(user_id) ON delete CASCADE,
  user_id2 integer NOT NULL REFERENCES users(user_id) ON delete CASCADE,
  PRIMARY KEY (user_id1, user_id2)
);

create TABLE IF NOT EXISTS film_genre (
  film_id bigint REFERENCES films (film_id) NOT NULL,
  genre_id integer REFERENCES genre (genre_id) NOT NULL
);

create TABLE IF NOT EXISTS film_likes (
  film_id bigint REFERENCES films (film_id) NOT NULL,
  user_id bigint REFERENCES users (user_id) NOT NULL
);